### PR TITLE
[#5] Footer icons are not centered

### PR DESCRIPTION
**Pull request by joeyshi12**
## Changes
- Centered footer icons using flexbox and removed width property on icon links to prevent icon images from overflowing out of the `externalLinks` div
- Pulled compliment button logic into separate file `js/compliment.js` and added rainbow styling to compliment paragraph.

image

### CODE REVIEW

**Comment by joeyshi12** [comment]
Plz lemme merge it

**Comment by 102plee** [comment]
There are some pressing security issues in this pull request that I have to look into. I'll get back to you ASAP in 2~3 business years.

**Comment by joeyshi12** [comment]
> There are some pressing security issues in this pull request that I have to look into. I'll get back to you ASAP in 2~3 business years.

>:(

**Comment by joeyshi12** [comment]
plzplzplz

**Comment by joeyshi12** [comment]
lemmemerge

**Pull request closed without merging**
